global using System.Threading.Tasks;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using Appllication.Repositories;
global using Infra.Entities;
global using Infra.Persitence;
global using Microsoft.EntityFrameworkCore;